language: go
go:
  - '1.11'

install:
  - go get -u golang.org/x/lint/golint
  - go get github.com/mattn/goveralls

before_script:
  - make check

script:
  - make test-cover

after_success:
  - $HOME/gopath/bin/goveralls -coverprofile=cover.out -service=travis-ci
