// Code generated by cmd/rte-gen/gen.go DO NOT EDIT.
package funcs_test

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/jwilner/rte"
)

func TestFuncs(t *testing.T) {
	for _, c := range []struct {
		Name, Route, Path string
		Handler           interface{}
		ErrMsg, Expected  string
	}{
		{
			Name:    "invalid-handler",
			Route:   "/",
			Path:    "/",
			Handler: func() {},
			ErrMsg:  "route 0 \"GET /\": handler has an unsupported signature: unknown handler type: func()",
		},
		{
			Name:  "func0-handler",
			Route: "/",
			Path:  "/",
			Handler: http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				_ = json.NewEncoder(w).Encode([]string{})
			}),
			Expected: "[]\n",
		},
		{
			Name:  "func0",
			Route: "/",
			Path:  "/",
			Handler: func(w http.ResponseWriter, r *http.Request) {
				_ = json.NewEncoder(w).Encode([]string{})
			},
			Expected: "[]\n",
		},
		{
			Name:  "func1",
			Route: "/:var-p0",
			Path:  "/p0",
			Handler: func(w http.ResponseWriter, r *http.Request, p0 string) {
				_ = json.NewEncoder(w).Encode([]string{
					p0,
				})
			},
			Expected: "[\"p0\"]\n",
		},
		{
			Name:  "arrFunc1",
			Route: "/:var-p0",
			Path:  "/p0",
			Handler: func(w http.ResponseWriter, r *http.Request, pVars [1]string) {
				_ = json.NewEncoder(w).Encode(pVars)
			},
			Expected: "[\"p0\"]\n",
		},
		{
			Name:  "func2",
			Route: "/:var-p0/:var-p1",
			Path:  "/p0/p1",
			Handler: func(w http.ResponseWriter, r *http.Request, p0, p1 string) {
				_ = json.NewEncoder(w).Encode([]string{
					p0,
					p1,
				})
			},
			Expected: "[\"p0\",\"p1\"]\n",
		},
		{
			Name:  "arrFunc2",
			Route: "/:var-p0/:var-p1",
			Path:  "/p0/p1",
			Handler: func(w http.ResponseWriter, r *http.Request, pVars [2]string) {
				_ = json.NewEncoder(w).Encode(pVars)
			},
			Expected: "[\"p0\",\"p1\"]\n",
		},
		{
			Name:  "func3",
			Route: "/:var-p0/:var-p1/:var-p2",
			Path:  "/p0/p1/p2",
			Handler: func(w http.ResponseWriter, r *http.Request, p0, p1, p2 string) {
				_ = json.NewEncoder(w).Encode([]string{
					p0,
					p1,
					p2,
				})
			},
			Expected: "[\"p0\",\"p1\",\"p2\"]\n",
		},
		{
			Name:  "arrFunc3",
			Route: "/:var-p0/:var-p1/:var-p2",
			Path:  "/p0/p1/p2",
			Handler: func(w http.ResponseWriter, r *http.Request, pVars [3]string) {
				_ = json.NewEncoder(w).Encode(pVars)
			},
			Expected: "[\"p0\",\"p1\",\"p2\"]\n",
		},
		{
			Name:  "func4",
			Route: "/:var-p0/:var-p1/:var-p2/:var-p3",
			Path:  "/p0/p1/p2/p3",
			Handler: func(w http.ResponseWriter, r *http.Request, p0, p1, p2, p3 string) {
				_ = json.NewEncoder(w).Encode([]string{
					p0,
					p1,
					p2,
					p3,
				})
			},
			Expected: "[\"p0\",\"p1\",\"p2\",\"p3\"]\n",
		},
		{
			Name:  "arrFunc4",
			Route: "/:var-p0/:var-p1/:var-p2/:var-p3",
			Path:  "/p0/p1/p2/p3",
			Handler: func(w http.ResponseWriter, r *http.Request, pVars [4]string) {
				_ = json.NewEncoder(w).Encode(pVars)
			},
			Expected: "[\"p0\",\"p1\",\"p2\",\"p3\"]\n",
		},
		{
			Name:  "arrFunc5",
			Route: "/:var-p0/:var-p1/:var-p2/:var-p3/:var-p4",
			Path:  "/p0/p1/p2/p3/p4",
			Handler: func(w http.ResponseWriter, r *http.Request, pVars [5]string) {
				_ = json.NewEncoder(w).Encode(pVars)
			},
			Expected: "[\"p0\",\"p1\",\"p2\",\"p3\",\"p4\"]\n",
		},
		{
			Name:  "arrFunc6",
			Route: "/:var-p0/:var-p1/:var-p2/:var-p3/:var-p4/:var-p5",
			Path:  "/p0/p1/p2/p3/p4/p5",
			Handler: func(w http.ResponseWriter, r *http.Request, pVars [6]string) {
				_ = json.NewEncoder(w).Encode(pVars)
			},
			Expected: "[\"p0\",\"p1\",\"p2\",\"p3\",\"p4\",\"p5\"]\n",
		},
		{
			Name:  "arrFunc7",
			Route: "/:var-p0/:var-p1/:var-p2/:var-p3/:var-p4/:var-p5/:var-p6",
			Path:  "/p0/p1/p2/p3/p4/p5/p6",
			Handler: func(w http.ResponseWriter, r *http.Request, pVars [7]string) {
				_ = json.NewEncoder(w).Encode(pVars)
			},
			Expected: "[\"p0\",\"p1\",\"p2\",\"p3\",\"p4\",\"p5\",\"p6\"]\n",
		},
		{
			Name:  "arrFunc8",
			Route: "/:var-p0/:var-p1/:var-p2/:var-p3/:var-p4/:var-p5/:var-p6/:var-p7",
			Path:  "/p0/p1/p2/p3/p4/p5/p6/p7",
			Handler: func(w http.ResponseWriter, r *http.Request, pVars [8]string) {
				_ = json.NewEncoder(w).Encode(pVars)
			},
			Expected: "[\"p0\",\"p1\",\"p2\",\"p3\",\"p4\",\"p5\",\"p6\",\"p7\"]\n",
		},
	} {
		t.Run(c.Name, func(t *testing.T) {
			tbl, err := rte.New([]rte.Route{
				{
					Method:  "GET",
					Path:    c.Route,
					Handler: c.Handler,
				},
			})

			if c.ErrMsg != "" {
				found := ""
				if err != nil {
					found = err.Error()
				}
				if found != c.ErrMsg {
					t.Fatalf("Wanted error %q but got %q", c.ErrMsg, found)
				}
			} else {
				w := httptest.NewRecorder()
				tbl.ServeHTTP(w, httptest.NewRequest("GET", c.Path, nil))

				if body := w.Body.String(); body != c.Expected {
					t.Fatalf("resp: got %q, %q", body, c.Expected)
				}
			}
		})
	}
}

func BenchmarkFuncs(b *testing.B) {
	for _, c := range []struct {
		Name    string
		Route   string
		Path    string
		Handler interface{}
	}{
		{
			"func0",
			"/",
			"/",
			func(w http.ResponseWriter, r *http.Request) {
			},
		},
		{
			"func1",
			"/:var-p0",
			"/p0",
			func(w http.ResponseWriter, r *http.Request, p0 string) {
			},
		},
		{
			"arrFunc1",
			"/:var-p0",
			"/p0",
			func(w http.ResponseWriter, r *http.Request, pVars [1]string) {
			},
		},
		{
			"func2",
			"/:var-p0/:var-p1",
			"/p0/p1",
			func(w http.ResponseWriter, r *http.Request, p0, p1 string) {
			},
		},
		{
			"arrFunc2",
			"/:var-p0/:var-p1",
			"/p0/p1",
			func(w http.ResponseWriter, r *http.Request, pVars [2]string) {
			},
		},
		{
			"func3",
			"/:var-p0/:var-p1/:var-p2",
			"/p0/p1/p2",
			func(w http.ResponseWriter, r *http.Request, p0, p1, p2 string) {
			},
		},
		{
			"arrFunc3",
			"/:var-p0/:var-p1/:var-p2",
			"/p0/p1/p2",
			func(w http.ResponseWriter, r *http.Request, pVars [3]string) {
			},
		},
		{
			"func4",
			"/:var-p0/:var-p1/:var-p2/:var-p3",
			"/p0/p1/p2/p3",
			func(w http.ResponseWriter, r *http.Request, p0, p1, p2, p3 string) {
			},
		},
		{
			"arrFunc4",
			"/:var-p0/:var-p1/:var-p2/:var-p3",
			"/p0/p1/p2/p3",
			func(w http.ResponseWriter, r *http.Request, pVars [4]string) {
			},
		},
		{
			"arrFunc5",
			"/:var-p0/:var-p1/:var-p2/:var-p3/:var-p4",
			"/p0/p1/p2/p3/p4",
			func(w http.ResponseWriter, r *http.Request, pVars [5]string) {
			},
		},
		{
			"arrFunc6",
			"/:var-p0/:var-p1/:var-p2/:var-p3/:var-p4/:var-p5",
			"/p0/p1/p2/p3/p4/p5",
			func(w http.ResponseWriter, r *http.Request, pVars [6]string) {
			},
		},
		{
			"arrFunc7",
			"/:var-p0/:var-p1/:var-p2/:var-p3/:var-p4/:var-p5/:var-p6",
			"/p0/p1/p2/p3/p4/p5/p6",
			func(w http.ResponseWriter, r *http.Request, pVars [7]string) {
			},
		},
		{
			"arrFunc8",
			"/:var-p0/:var-p1/:var-p2/:var-p3/:var-p4/:var-p5/:var-p6/:var-p7",
			"/p0/p1/p2/p3/p4/p5/p6/p7",
			func(w http.ResponseWriter, r *http.Request, pVars [8]string) {
			},
		},
	} {
		b.Run(c.Name, func(b *testing.B) {
			tbl := rte.Must([]rte.Route{
				{
					Method:  "GET",
					Path:    c.Route,
					Handler: c.Handler,
				},
			})
			r := httptest.NewRequest("GET", c.Path, nil)
			w := httptest.NewRecorder()

			b.ReportAllocs()
			b.ResetTimer()
			for i := 0; i < b.N; i++ {
				tbl.ServeHTTP(w, r)
			}
		})
	}
}
