// Code generated by cmd/rte-gen/gen.go DO NOT EDIT.
package funcs_test

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/jwilner/rte"
)

func TestFuncs(t *testing.T) {
	for _, c := range []struct {
		Name     string
		Route    string
		Path     string
		Handler  interface{}
		Expected string
	}{
		{
			"func0-handler",
			"/",
			"/",
			http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				_ = json.NewEncoder(w).Encode([]string{})
			}),
			"[]\n",
		},
		{
			"func0",
			"/",
			"/",
			func(w http.ResponseWriter, r *http.Request) {
				_ = json.NewEncoder(w).Encode([]string{})
			},
			"[]\n",
		},
		{
			"func1",
			"/:var-p0",
			"/p0",
			func(w http.ResponseWriter, r *http.Request, p0 string) {
				_ = json.NewEncoder(w).Encode([]string{
					p0,
				})
			},
			"[\"p0\"]\n",
		},
		{
			"arrFunc1",
			"/:var-p0",
			"/p0",
			func(w http.ResponseWriter, r *http.Request, pVars [1]string) {
				_ = json.NewEncoder(w).Encode(pVars)
			},
			"[\"p0\"]\n",
		},
		{
			"func2",
			"/:var-p0/:var-p1",
			"/p0/p1",
			func(w http.ResponseWriter, r *http.Request, p0, p1 string) {
				_ = json.NewEncoder(w).Encode([]string{
					p0,
					p1,
				})
			},
			"[\"p0\",\"p1\"]\n",
		},
		{
			"arrFunc2",
			"/:var-p0/:var-p1",
			"/p0/p1",
			func(w http.ResponseWriter, r *http.Request, pVars [2]string) {
				_ = json.NewEncoder(w).Encode(pVars)
			},
			"[\"p0\",\"p1\"]\n",
		},
		{
			"func3",
			"/:var-p0/:var-p1/:var-p2",
			"/p0/p1/p2",
			func(w http.ResponseWriter, r *http.Request, p0, p1, p2 string) {
				_ = json.NewEncoder(w).Encode([]string{
					p0,
					p1,
					p2,
				})
			},
			"[\"p0\",\"p1\",\"p2\"]\n",
		},
		{
			"arrFunc3",
			"/:var-p0/:var-p1/:var-p2",
			"/p0/p1/p2",
			func(w http.ResponseWriter, r *http.Request, pVars [3]string) {
				_ = json.NewEncoder(w).Encode(pVars)
			},
			"[\"p0\",\"p1\",\"p2\"]\n",
		},
		{
			"func4",
			"/:var-p0/:var-p1/:var-p2/:var-p3",
			"/p0/p1/p2/p3",
			func(w http.ResponseWriter, r *http.Request, p0, p1, p2, p3 string) {
				_ = json.NewEncoder(w).Encode([]string{
					p0,
					p1,
					p2,
					p3,
				})
			},
			"[\"p0\",\"p1\",\"p2\",\"p3\"]\n",
		},
		{
			"arrFunc4",
			"/:var-p0/:var-p1/:var-p2/:var-p3",
			"/p0/p1/p2/p3",
			func(w http.ResponseWriter, r *http.Request, pVars [4]string) {
				_ = json.NewEncoder(w).Encode(pVars)
			},
			"[\"p0\",\"p1\",\"p2\",\"p3\"]\n",
		},
		{
			"arrFunc5",
			"/:var-p0/:var-p1/:var-p2/:var-p3/:var-p4",
			"/p0/p1/p2/p3/p4",
			func(w http.ResponseWriter, r *http.Request, pVars [5]string) {
				_ = json.NewEncoder(w).Encode(pVars)
			},
			"[\"p0\",\"p1\",\"p2\",\"p3\",\"p4\"]\n",
		},
		{
			"arrFunc6",
			"/:var-p0/:var-p1/:var-p2/:var-p3/:var-p4/:var-p5",
			"/p0/p1/p2/p3/p4/p5",
			func(w http.ResponseWriter, r *http.Request, pVars [6]string) {
				_ = json.NewEncoder(w).Encode(pVars)
			},
			"[\"p0\",\"p1\",\"p2\",\"p3\",\"p4\",\"p5\"]\n",
		},
		{
			"arrFunc7",
			"/:var-p0/:var-p1/:var-p2/:var-p3/:var-p4/:var-p5/:var-p6",
			"/p0/p1/p2/p3/p4/p5/p6",
			func(w http.ResponseWriter, r *http.Request, pVars [7]string) {
				_ = json.NewEncoder(w).Encode(pVars)
			},
			"[\"p0\",\"p1\",\"p2\",\"p3\",\"p4\",\"p5\",\"p6\"]\n",
		},
		{
			"arrFunc8",
			"/:var-p0/:var-p1/:var-p2/:var-p3/:var-p4/:var-p5/:var-p6/:var-p7",
			"/p0/p1/p2/p3/p4/p5/p6/p7",
			func(w http.ResponseWriter, r *http.Request, pVars [8]string) {
				_ = json.NewEncoder(w).Encode(pVars)
			},
			"[\"p0\",\"p1\",\"p2\",\"p3\",\"p4\",\"p5\",\"p6\",\"p7\"]\n",
		},
	} {
		t.Run(c.Name, func(t *testing.T) {
			tbl := rte.Must([]rte.Route{
				{
					Method:  "GET",
					Path:    c.Route,
					Handler: c.Handler,
				},
			})

			w := httptest.NewRecorder()
			tbl.ServeHTTP(w, httptest.NewRequest("GET", c.Path, nil))

			if body := w.Body.String(); body != c.Expected {
				t.Fatalf("resp: got %q, %q", body, c.Expected)
			}
		})
	}
}

func BenchmarkFuncs(b *testing.B) {
	for _, c := range []struct {
		Name    string
		Route   string
		Path    string
		Handler interface{}
	}{
		{
			"func0",
			"/",
			"/",
			func(w http.ResponseWriter, r *http.Request) {
			},
		},
		{
			"func1",
			"/:var-p0",
			"/p0",
			func(w http.ResponseWriter, r *http.Request, p0 string) {
			},
		},
		{
			"arrFunc1",
			"/:var-p0",
			"/p0",
			func(w http.ResponseWriter, r *http.Request, pVars [1]string) {
			},
		},
		{
			"func2",
			"/:var-p0/:var-p1",
			"/p0/p1",
			func(w http.ResponseWriter, r *http.Request, p0, p1 string) {
			},
		},
		{
			"arrFunc2",
			"/:var-p0/:var-p1",
			"/p0/p1",
			func(w http.ResponseWriter, r *http.Request, pVars [2]string) {
			},
		},
		{
			"func3",
			"/:var-p0/:var-p1/:var-p2",
			"/p0/p1/p2",
			func(w http.ResponseWriter, r *http.Request, p0, p1, p2 string) {
			},
		},
		{
			"arrFunc3",
			"/:var-p0/:var-p1/:var-p2",
			"/p0/p1/p2",
			func(w http.ResponseWriter, r *http.Request, pVars [3]string) {
			},
		},
		{
			"func4",
			"/:var-p0/:var-p1/:var-p2/:var-p3",
			"/p0/p1/p2/p3",
			func(w http.ResponseWriter, r *http.Request, p0, p1, p2, p3 string) {
			},
		},
		{
			"arrFunc4",
			"/:var-p0/:var-p1/:var-p2/:var-p3",
			"/p0/p1/p2/p3",
			func(w http.ResponseWriter, r *http.Request, pVars [4]string) {
			},
		},
		{
			"arrFunc5",
			"/:var-p0/:var-p1/:var-p2/:var-p3/:var-p4",
			"/p0/p1/p2/p3/p4",
			func(w http.ResponseWriter, r *http.Request, pVars [5]string) {
			},
		},
		{
			"arrFunc6",
			"/:var-p0/:var-p1/:var-p2/:var-p3/:var-p4/:var-p5",
			"/p0/p1/p2/p3/p4/p5",
			func(w http.ResponseWriter, r *http.Request, pVars [6]string) {
			},
		},
		{
			"arrFunc7",
			"/:var-p0/:var-p1/:var-p2/:var-p3/:var-p4/:var-p5/:var-p6",
			"/p0/p1/p2/p3/p4/p5/p6",
			func(w http.ResponseWriter, r *http.Request, pVars [7]string) {
			},
		},
		{
			"arrFunc8",
			"/:var-p0/:var-p1/:var-p2/:var-p3/:var-p4/:var-p5/:var-p6/:var-p7",
			"/p0/p1/p2/p3/p4/p5/p6/p7",
			func(w http.ResponseWriter, r *http.Request, pVars [8]string) {
			},
		},
	} {
		b.Run(c.Name, func(b *testing.B) {
			tbl := rte.Must([]rte.Route{
				{
					Method:  "GET",
					Path:    c.Route,
					Handler: c.Handler,
				},
			})
			r := httptest.NewRequest("GET", c.Path, nil)
			w := httptest.NewRecorder()

			b.ReportAllocs()
			b.ResetTimer()
			for i := 0; i < b.N; i++ {
				tbl.ServeHTTP(w, r)
			}
		})
	}
}
